-- Users (app users)
create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  email text unique,
  mobile text unique,
  role text not null check (role in ('admin','user')) default 'user',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Admin credentials (username/password hash), optional if using Auth
create table if not exists public.admin_credentials (
  username text primary key,
  password_hash text not null,
  email text,
  role text not null check (role in ('admin','super_admin')) default 'admin',
  last_login timestamptz,
  created_at timestamptz not null default now()
);

-- Categories
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  description text,
  image text,
  product_count int not null default 0,
  type text not null check (type in ('jewel','gemstone'))
);

-- Products
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12,2) not null,
  image text,
  hint text,
  description text,
  category_id bigint not null references public.categories(id) on delete cascade,
  sub_category text,
  sub_heading text
);

-- Inquiries
create table if not exists public.inquiries (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  name text not null,
  email text,
  mobile text not null,
  message text not null,
  product_id bigint references public.products(id) on delete set null,
  product_name text,
  status text not null check (status in ('new','resolved')) default 'new'
);

-- Bank details (single row)
create table if not exists public.bank_details (
  id boolean primary key default true,
  account_holder text not null,
  bank_name text not null,
  account_number text not null,
  ifsc_code text not null,
  account_type text not null,
  upi_id text,
  qr_image_url text
);

-- Additional columns
alter table public.bank_details add column if not exists gst_number text;
alter table public.bank_details add column if not exists gst_details text;

-- RLS policies (example - adjust as needed)
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.inquiries enable row level security;
alter table public.users enable row level security;
alter table public.bank_details enable row level security;

-- Public read policies for catalog
create policy "Public read categories" on public.categories for select using (true);
create policy "Public read products" on public.products for select using (true);
create policy "Public insert inquiries" on public.inquiries for insert with check (true);
create policy "Admin manage bank details" on public.bank_details for all using (auth.role() = 'authenticated');


